= IVP - Meters - Reports (Legacy) - All Meters
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Get readings from all the meters (Legacy).

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/ivp/meters/reports/` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../../../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`createdAt`
|Number
|Number
|The epoch date and time the message was generated.

|`reportType`
|String
|`MeasurementType` (e.g. `production`)
|What type of measurement this is reporting. In the format `MeasurementType`.

|`cumulative`
|Object
|`MeterReading` object
|The cumulative results of all the phases.

|`lines`
|Array(Object)
|Array of `MeterReading`
|The results for each of the phases.

|===

=== `MeterReading` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`currW`
|Number
|Number
|The current number of Watts.

|`actPower`
|Number
|Number
|The active power.

|`apprntPwr`
|Number
|Number
|The apparent power.

|`reactPwr`
|Number
|Number
|The reactive power.

|`whDlvdCum`
|Number
|Number
|The cumulative watt-hour delivered.

|`whRcvdCum`
|Number
|Number
|The cumulative watt-hour received.

|`varhLagCum`
|Number
|Number
|The cumulative lagging varh.

|`varhLeadCum`
|Number
|Number
|The cumulative leading varh.

|`vahCum`
|Number
|Number
|The cumulative vah.

|`rmsVoltage`
|Number
|Number
|The rms Voltage.

|`rmsCurrent`
|Number
|Number
|The rms Current.

|`pwrFactor`
|Number
|Number
|The power factor.

|`freqHz`
|Number
|Number
|The frequency in Hz.

|===

== Types

=== `MeasurementType` Type

[cols="1,1,2", options="header"]
|===
|Value
|Name
|Description

|`production`
|Production
|Reporting the energy produced from the inverters.

|`net-consumption`
|Net Consumption
|Reporting the load with solar production included.

|`total-consumption`
|Total Consumption
|Reporting the load only (solar production excluded).

|===

== Examples

=== Get Meters' Readings

.GET */ivp/meters/reports/* Response
[source,json,subs="+quotes"]
----
[{"createdAt": 1686961552, "reportType": "production", "cumulative": {"currW": 0.591, "actPower": 0.591, "apprntPwr": 254.555, "reactPwr": 248.904, "whDlvdCum": 2485013.732, "whRcvdCum": 11887.499, "varhLagCum": 795781.345, "varhLeadCum": 0.398, "vahCum": 3054493.114, "rmsVoltage": 243.958, "rmsCurrent": 1.043, "pwrFactor": 0.0, "freqHz": 50.12}, "lines": [{"currW": 0.591, "actPower": 0.591, "apprntPwr": 254.555, "reactPwr": 248.904, "whDlvdCum": 2485013.732, "whRcvdCum": 11887.499, "varhLagCum": 795781.345, "varhLeadCum": 0.398, "vahCum": 3054493.114, "rmsVoltage": 243.958, "rmsCurrent": 1.043, "pwrFactor": 0.0, "freqHz": 50.12}]}, {"createdAt": 1686961552, "reportType": "net-consumption", "cumulative": {"currW": 434.245, "actPower": 434.245, "apprntPwr": 972.372, "reactPwr": -792.063, "whDlvdCum": 1749552.725, "whRcvdCum": 1601637.637, "varhLagCum": 17.665, "varhLeadCum": 2831880.565, "vahCum": 5069070.805, "rmsVoltage": 243.888, "rmsCurrent": 3.987, "pwrFactor": 0.44, "freqHz": 50.12}, "lines": [{"currW": 434.245, "actPower": 434.245, "apprntPwr": 972.372, "reactPwr": -792.063, "whDlvdCum": 1749552.725, "whRcvdCum": 1601637.637, "varhLagCum": 17.665, "varhLeadCum": 2831880.565, "vahCum": 5069070.805, "rmsVoltage": 243.888, "rmsCurrent": 3.987, "pwrFactor": 0.44, "freqHz": 50.12}]}, {"createdAt": 1686961552, "reportType": "total-consumption", "cumulative": {"currW": 434.836, "actPower": 434.836, "apprntPwr": 1226.868, "reactPwr": -1040.967, "whDlvdCum": 2631392.206, "whRcvdCum": 0.0, "varhLagCum": 795799.01, "varhLeadCum": 2831880.963, "vahCum": 5069070.805, "rmsVoltage": 243.923, "rmsCurrent": 5.03, "pwrFactor": 0.35, "freqHz": 50.12}, "lines": [{"currW": 434.836, "actPower": 434.836, "apprntPwr": 1226.868, "reactPwr": -1040.967, "whDlvdCum": 2631401.67, "whRcvdCum": 0.0, "varhLagCum": 795799.01, "varhLeadCum": 2831880.963, "vahCum": 5069070.805, "rmsVoltage": 243.923, "rmsCurrent": 5.03, "pwrFactor": 0.35, "freqHz": 50.12}]}]
----