= IVP - Meters - Reports (Legacy) - Consumption Only
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Get readings from the consumption meters (Legacy).

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/ivp/meters/reports/consumption` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../../../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`createdAt`
|Number
|Number
|The epoch date and time the message was generated.

|`reportType`
|String
|`MeasurementType` (e.g. `net-consumption`)
|What type of measurement this is reporting. In the format `MeasurementType`.

|`cumulative`
|Object
|`MeterReading` object
|The cumulative results of all the phases.

|`lines`
|Array(Object)
|Array of `MeterReading`
|The results for each of the phases.

|===

=== `MeterReading` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`currW`
|Number
|Number
|The current number of Watts.

|`actPower`
|Number
|Number
|The active power.

|`apprntPwr`
|Number
|Number
|The apparent power.

|`reactPwr`
|Number
|Number
|The reactive power.

|`whDlvdCum`
|Number
|Number
|The cumulative watt-hour delivered.

|`whRcvdCum`
|Number
|Number
|The cumulative watt-hour received.

|`varhLagCum`
|Number
|Number
|The cumulative lagging varh.

|`varhLeadCum`
|Number
|Number
|The cumulative leading varh.

|`vahCum`
|Number
|Number
|The cumulative vah.

|`rmsVoltage`
|Number
|Number
|The rms Voltage.

|`rmsCurrent`
|Number
|Number
|The rms Current.

|`pwrFactor`
|Number
|Number
|The power factor.

|`freqHz`
|Number
|Number
|The frequency in Hz.

|===

== Types

=== `MeasurementType` Type

[cols="1,1,2", options="header"]
|===
|Value
|Name
|Description

|`net-consumption`
|Net Consumption
|Reporting the load with solar production included.

|`total-consumption`
|Total Consumption
|Reporting the load only (solar production excluded).

|===

== Examples

=== Get Consumption Meter Reading Information

.GET */ivp/meters/reports/consumption* Response
[source,json,subs="+quotes"]
----
[{"createdAt": 1686961636, "reportType": "total-consumption", "cumulative": {"currW": 435.983, "actPower": 435.983, "apprntPwr": 1228.326, "reactPwr": -1041.54, "whDlvdCum": 2631402.389, "whRcvdCum": 0.0, "varhLagCum": 795804.842, "varhLeadCum": 2831899.533, "vahCum": 5069093.617, "rmsVoltage": 243.847, "rmsCurrent": 5.037, "pwrFactor": 0.35, "freqHz": 50.12}, "lines": [{"currW": 435.983, "actPower": 435.983, "apprntPwr": 1228.326, "reactPwr": -1041.54, "whDlvdCum": 2631411.854, "whRcvdCum": 0.0, "varhLagCum": 795804.842, "varhLeadCum": 2831899.533, "vahCum": 5069093.617, "rmsVoltage": 243.847, "rmsCurrent": 5.037, "pwrFactor": 0.35, "freqHz": 50.12}]}, {"createdAt": 1686961636, "reportType": "net-consumption", "cumulative": {"currW": 435.311, "actPower": 435.311, "apprntPwr": 974.38, "reactPwr": -792.26, "whDlvdCum": 1749562.897, "whRcvdCum": 1601637.637, "varhLagCum": 17.665, "varhLeadCum": 2831899.135, "vahCum": 5069093.617, "rmsVoltage": 243.847, "rmsCurrent": 3.992, "pwrFactor": 0.45, "freqHz": 50.12}, "lines": [{"currW": 435.311, "actPower": 435.311, "apprntPwr": 974.38, "reactPwr": -792.26, "whDlvdCum": 1749562.897, "whRcvdCum": 1601637.637, "varhLagCum": 17.665, "varhLeadCum": 2831899.135, "vahCum": 5069093.617, "rmsVoltage": 243.847, "rmsCurrent": 3.992, "pwrFactor": 0.45, "freqHz": 50.12}]}]
----