= IVP - Zigbee - Reset Device
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Reset device for "IQ System Controller" (formerly "Enpower") manual override. The Gateway (formerly "Envoy") communicates with both the IQ System Controller (formerly "Enpower") before version 3 and the IQ Battery (formerly "Encharge") before IQ battery 5P (i.e. IQ Battery 3, 3T, 10 and 10T) using Zigbee.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/ivp/zb/reset_device` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../../Auth/Check_JWT.adoc[Auth/Check_JWT].
