= IVP - Meters - General - Specific Meter’s Current Transformer (CT) Reversal
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Get or set specific meter’s Current Transformer (CT) clamp reverse polarity settings globally or by a meter identifier.

== Introduction

Get or set specific meter’s Current Transformer (CT) clamp reverse polarity settings globally, by meter type (`c` for consumption or `p` for production) or by a meter type and specific line identifier (`cL1`, `cL2`, `cL3`, `pL1`, `pL2` or `pL3`).

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the xref:../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/ivp/meters/ctreversal/{EID}` endpoint provides the following response data.

As of recent Gateway software versions this request requires user authentication and authorisation, see xref:../../Authentication.adoc[Authentication].

== Examples

=== Get All Meters' CT Reversal Settings

.GET */ivp/meters/ctreversal/* Response
[source,json,subs="+quotes"]
----
{}
----

=== Get Consumption Meters' Line #1 CT Reversal Settings

.GET */ivp/meters/ctreversal/cL1* Response
[source,json,subs="+quotes"]
----
{}
----