= Admin - Lib - Wireless Configuration
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Get or set the wireless settings.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/admin/lib/wireless_display.json` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`supported`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether this Gateway (formerly "Envoy") supports connecting to Wi-Fi.

|`present`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether the Wi-Fi adapter is currently present.

|`configured`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether a Wi-Fi network is configured.

|`up`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether the Wi-Fi interface is currently connected.

|`carrier`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether the configured Wi-Fi network is currently available.

|`current_network`
|Object
|`CurrentNetwork` object
|Details about the current connected Wi-Fi network.

|`device_info`
|Object
|`DeviceInfo` object
|Details about the Wi-Fi adapter.

|`ap_mode`
|Object
|`APMode` object
|Details about this Gateway’s (formerly "Envoy") access point mode.

|`selected_region`
|String
|String
|The selected legislative region the Wi-Fi adapter is operating in.

|`regions`
|Array(String)
|Array of String
|List of available legislative regions that the Wi-Fi adapter can operate in.

|`sites` (Optional)
|Array(Object)
|Array of `Site`
|A list of available Wi-Fi networks.

|===

=== `CurrentNetwork` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`ssid`
|String
|String
|The Wi-Fi network’s Service Set IDentifier (SSID).

|`status`
|String
|String
|The status of the Wi-Fi connection.

|`ip_address`
|String
|String
|The Internet Protocol (IP) address of this interface.

|`gateway_ip`
|String
|String
|The Internet Protocol (IP) address of the gateway

|`security_mode`
|String
|String
|The version of security this Wi-Fi network is operating.

|`encryption_type`
|String
|String
|The type of encryption this Wi-Fi network is operating with.

|`ap_bssid`
|String
|String
|The Access Point (AP)’s Basic Service Set Identifier (BSSID)

|`channel`
|String
|String
|The channel (or frequency) this Wi-Fi network is currently operating on.

|`bars`
|Number
|Number
|The current signal strength in bars.

|===

=== `DeviceInfo` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`vendor`
|String
|String
|The vendor of the Wi-Fi adapter.

|`device`
|String
|String
|The name of the device.

|`vendor_id`
|String
|String
|The vendor identifier.

|`device_id`
|String
|String
|The device identifier.

|`manufacturer`
|String
|String
|The manufacturer of the device.

|`model`
|String
|String
|The model of the device.

|`serial`
|String
|String
|The serial number of the device.

|`hw_version`
|String
|String
|The hardware version of the device.

|`usb_spec`
|String
|String
|The USB specification version.

|`usb_slot`
|String
|String
|The USB slot the device is inserted into.

|`driver`
|String
|String
|The name of the Wi-Fi adapter driver.

|`mac`
|String
|String
|The Media Access Control (MAC) address of the adapter.

|===

=== `APMode` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`enabled`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether the Gateway (formerly "Envoy") is currently acting as an Access Point (AP).

|`name`
|String
|String
|The broadcast name of the Gateway’s (formerly "Envoy") Wi-Fi Access Point (AP) name.

|===

=== `Site` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`is_current_ssid`
|Boolean
|Boolean (e.g. `true` or `false`)
|Is this the same Service Set IDentifier (SSID) as the current configured network.

|`mac`
|String
|String
|The Access Point (AP)’s Basic Service Set Identifier (BSSID)

|`channel`
|String
|String
|The channel (or frequency) the Access Point is currently operating on.

|`ssid`
|String
|String
|The Wi-Fi network’s Service Set IDentifier (SSID).

|`bars`
|Number
|Number
|The current signal strength in bars.

|`secured`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether or not the Wi-Fi network has any configured security.

|`wps`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether Wi-Fi Protected Setup is enabled.

|`unsupported`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether this Gateway (formerly "Envoy") is unable to support connecting to this Wi-Fi network.

|`security_mode`
|String
|String
|The version of security this Wi-Fi network is operating.

|`encryption_type`
|String
|String
|The type of encryption this Wi-Fi network is operating with.

|===

== Examples

=== Get Wireless Configuration

.GET */admin/lib/wireless_display.json* Response
[source,json,subs="+quotes"]
----
{"supported": true, "present": true, "configured": true, "up": true, "carrier": true, "current_network": {"ssid": "MyHome", "status": "connected", "ip_address": "192.168.0.100", "gateway_ip": "192.168.0.1", "security_mode": "WPA2-PSK", "encryption_type": "CCMP", "ap_bssid": "AA:BB:CC:DD:EE:FF", "channel": "36", "bars": 2}, "device_info": {"vendor": "Enphase", "device": "platform:wl18xx", "vendor_id": "", "device_id": "", "manufacturer": "Enphase", "model": "platform:wl18xx", "serial": "", "hw_version": "", "usb_spec": "", "usb_slot": "", "driver": "wl18xx_driver", "mac": "BB:BB:CC:DD:EE:FF"}, "ap_mode": {"enabled": false, "name": "ENVOY_099999"}, "selected_region": "GB", "regions": ["00", "AE", "AL", "AM", "AN", "AR", "AT", "AU", "AW", "AZ", "BA", "BB", "BD", "BE", "BG", "BH", "BL", "BN", "BO", "BR", "BY", "BZ", "CA", "CH", "CL", "CN", "CO", "CR", "CS", "CY", "CZ", "DE", "DK", "DO", "DZ", "EC", "EE", "EG", "ES", "FI", "FR", "GB", "GD", "GE", "GL", "GR", "GT", "GU", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IR", "IS", "IT", "JM", "JO", "JP", "KE", "KH", "KP", "KR", "KW", "KZ", "LB", "LI", "LK", "LT", "LU", "LV", "MA", "MC", "MK", "MO", "MT", "MX", "MY", "NL", "NO", "NP", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PR", "PT", "QA", "RO", "RU", "SA", "SE", "SG", "SI", "SK", "SV", "SY", "TH", "TN", "TR", "TT", "TW", "UA", "US", "UY", "UZ", "VE", "VN", "YE", "ZA", "ZW"], "sites": [{"is_current_ssid": false, "mac": "ff:ff:ff:ff:ff:ff", "channel": "5180", "ssid": "SomeoneElse", "bars": 2, "secured": false, "wps": false, "unsupported": false, "security_mode": "Open/Unsecured", "encryption_type": "NONE"}, {"is_current_ssid": false, "mac": "ee:cc:bb:aa:bb:cc", "channel": "5180", "ssid": "SomeoneElse2", "bars": 2, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "CCMP"}, {"is_current_ssid": false, "mac": "cc:cc:cc:dd:aa:cc", "channel": "5180", "ssid": "SomeoneElse3", "bars": 2, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "CCMP"}, {"is_current_ssid": false, "mac": "bb:bb:bb:bb:bb:bb", "channel": "2462", "ssid": "SomeoneElse4", "bars": 3, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "CCMP"}, {"is_current_ssid": true, "mac": "aa:bb:cc:dd:ee:ff", "channel": "5180", "ssid": "MyHome", "bars": 2, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "CCMP"}, {"is_current_ssid": false, "mac": "ff:ff:dd:cc:aa:aa", "channel": "2412", "ssid": "SomeoneElse4", "bars": 2, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "CCMP"}, {"is_current_ssid": false, "mac": "cc:cc:cc:cc:cc:cc", "channel": "2462", "ssid": "SomeoneElse5", "bars": 4, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "TKIP + CCMP"}, {"is_current_ssid": false, "mac": "aa:bb:cc:dd:ee:ff", "channel": "5260", "ssid": "SomeoneElse6", "bars": 1, "secured": true, "wps": false, "unsupported": false, "security_mode": "WPA2 Personal", "encryption_type": "CCMP"}]}
----

=== Get Wireless Configuration (No Site Info)

.GET */admin/lib/wireless_display.json?site_info=0* Response
[source,json,subs="+quotes"]
----
{"supported": true, "present": true, "configured": true, "up": true, "carrier": true, "current_network": {"ssid": "MyHome", "status": "connected", "ip_address": "192.168.0.100", "gateway_ip": "192.168.0.1", "security_mode": "WPA2-PSK", "encryption_type": "CCMP", "ap_bssid": "AA:BB:CC:DD:EE:FF", "channel": "36", "bars": 1}, "device_info": {"vendor": "Enphase", "device": "platform:wl18xx", "vendor_id": "", "device_id": "", "manufacturer": "Enphase", "model": "platform:wl18xx", "serial": "", "hw_version": "", "usb_spec": "", "usb_slot": "", "driver": "wl18xx_driver", "mac": "BB:BB:CC:DD:EE:FF"}, "ap_mode": {"enabled": false, "name": "ENVOY_099999"}, "selected_region": "GB", "regions": ["00", "AE", "AL", "AM", "AN", "AR", "AT", "AU", "AW", "AZ", "BA", "BB", "BD", "BE", "BG", "BH", "BL", "BN", "BO", "BR", "BY", "BZ", "CA", "CH", "CL", "CN", "CO", "CR", "CS", "CY", "CZ", "DE", "DK", "DO", "DZ", "EC", "EE", "EG", "ES", "FI", "FR", "GB", "GD", "GE", "GL", "GR", "GT", "GU", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IR", "IS", "IT", "JM", "JO", "JP", "KE", "KH", "KP", "KR", "KW", "KZ", "LB", "LI", "LK", "LT", "LU", "LV", "MA", "MC", "MK", "MO", "MT", "MX", "MY", "NL", "NO", "NP", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PR", "PT", "QA", "RO", "RU", "SA", "SE", "SG", "SI", "SK", "SV", "SY", "TH", "TN", "TR", "TT", "TW", "UA", "US", "UY", "UZ", "VE", "VN", "YE", "ZA", "ZW"]}
----