= Data Tables - Administer Device Conditions and Controls (DCC) DataTable
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Used by the JavaScript datatable (see http://legacy.datatables.net/usage/server-side) to return Device Conditions and Controls (DCC) records.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/datatab/admin_dcc_display_dt` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`sEcho`
|Number
|Number
|An unaltered copy of sEcho sent from the client side. This parameter will change with each table re-draw (it is basically a draw count) - so it is important that this is implemented.

|`iTotalRecords`
|Number
|Number
|Total records, before filtering (i.e. the total number of records in the database).

|`iTotalDisplayRecords`
|Number
|Number
|Total records, after filtering (i.e. the total number of records after filtering has been applied - not just the number of records being returned in this result set).

|`aaData`
|Array(Unknown)
|Array of Unknown
|The data in a 2D array (select, serial_num, part_num, dev_control, dev_condition, last_rpt_date).

|===

== Examples

=== Get Device Conditions and Controls (DCC) Events

.GET */datatab/admin_dcc_display_dt?name=adcdActiveTable&sColumns=select* Response
[source,json,subs="+quotes"]
----
{"sEcho": 0, "iTotalRecords": 14, "iTotalDisplayRecords": 14, "aaData": [["<input type=\"checkbox\" value=\"553648384\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627390225\">123456789101</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553648640\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627390481\">123456789102</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553648896\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627390737\">123456789103</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553649152\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627390993\">123456789104</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553649408\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627391249\">123456789105</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553649664\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627391505\">123456789106</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553649920\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627391761\">123456789107</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553650176\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627392017\">123456789108</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553650432\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627392273\">123456789109</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553650688\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627392529\">123456789110</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553650944\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627392785\">123456789111</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553651200\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627393041\">123456789112</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553651456\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627393297\">123456789113</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"], ["<input type=\"checkbox\" value=\"553651712\" name=\"selectDev\">", "<a href=\"/admin/lib/admin_dcc_display?locale=en&amp;eid=1627393553\">123456789114</a>", "800-01714-r02", "None<br>", "OK<br>", "Mon Jun 19, 2023 05:50 PM BST"]]}
----