= Data Tables - Inventory DataTable
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Used by the JavaScript datatable (see http://legacy.datatables.net/usage/server-side) to return inventory records.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/datatab/inventory_dt` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`sEcho`
|Number
|Number
|An unaltered copy of sEcho sent from the client side. This parameter will change with each table re-draw (it is basically a draw count) - so it is important that this is implemented.

|`iTotalRecords`
|Number
|Number
|Total records, before filtering (i.e. the total number of records in the database).

|`iTotalDisplayRecords`
|Number
|Number
|Total records, after filtering (i.e. the total number of records after filtering has been applied - not just the number of records being returned in this result set).

|`aaData`
|Array(Unknown)
|Array of Unknown
|The data in a 2D array (part_num, installed, serial_num, device_status, running_image, assem_part_num, ctrl_part_num, last_rpt_date).

|===

== Examples

=== Get Inventory

.GET */datatab/inventory_dt* Response
[source,json,subs="+quotes"]
----
{"sEcho": 0, "iTotalRecords": 14, "iTotalDisplayRecords": 14, "aaData": [["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789101", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789111", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789110", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789102", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789108", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789107", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789104", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789113", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:51 PM GMT", "123456789103", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Wed Dec 21, 2022 01:52 PM GMT", "123456789112", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Thu Mar 23, 2023 12:36 PM GMT", "123456789105", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Thu Mar 23, 2023 12:36 PM GMT", "123456789114", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Thu Mar 23, 2023 12:36 PM GMT", "123456789109", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"], ["800-01714-r02", "Thu Mar 23, 2023 12:37 PM GMT", "123456789106", "OK<br>", "520-00082-r01-v04.27.04 - Mon Feb 15, 2021 04:04 PM GMT", "880-00791-r09", "480-00031-r01-v00.0c.01", "Mon Jun 19, 2023 04:19 PM BST"]]}
----