= Installer - Advanced Grid Functionality (AGF) - Index
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

List uploaded Advanced Grid Functionality (AGF) profile(s).

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the xref:../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/installer/agf/index.json` endpoint provides the following response data.

As of recent Gateway software versions this request requires user authentication and authorisation, see xref:../../Authentication.adoc[Authentication].

=== Querystring

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`simplified` (Optional)
|Boolean
|Boolean (e.g. `0` or `1`)
|Used by the installer toolkit, if set to true will remove duplicate profile names.

|===

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`selected_profile`
|String
|String
|The currently selected Advanced Grid Functionality (AGF) Profile.

|`selected_profile_id`
|String
|String
|The unique ID of the currently selected profile.

|`last_package_profile_md5sum`
|String
|String
|The MD5 checksum of the last package profile.

|`profile_auto_selected`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether a profile has been automatically selected.

|`mm_version`
|String
|String
|Master Model (MM) version.

|`bt_version`
|String
|String
|Base Template (BT) version.

|`migration_in_progress`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether profile migration script is running.

|`profiles`
|Array(Object)
|Array of `Profiles`
|The list of profiles on the device.

|`profile_groups`
|Object
|`Profile_groups` object
|The list of profiles on the device sorted into groups.

|===

=== `Profiles` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`uuid`
|String
|String
|The unique identifier for the profile.

|`profile_id`
|String
|String
|The profile identification name (including version number).

|`profile_name`
|String
|String
|The profile name.

|`profile_version`
|String
|String
|The profile version.

|`profile_description`
|String
|String
|The profile description.

|`policy`
|Object
|`Profiles.Policy` object
|Details of the criteria to be allowed to use this profile.

|`envoy_type`
|String
|String
|The region of the Gateway (formerly "Envoy") that is able to use this profile.

|`countries`
|Array(String)
|Array of String
|The countries this profile can be applied to.

|`states`
|Array(Unknown)
|Array of Unknown
|The states this profile can be applied to.

|`unpacked`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether the profile has been unpacked on the device.

|`profile_source`
|Array(String)
|Array of String
|Where the profile was obtained from.

|`dynamic`
|Boolean
|Boolean (e.g. `true` or `false`)
|???

|`mm_version`
|String
|String
|Master Model (MM) version.

|`bt_version`
|String
|String
|Base Template (BT) version.

|===

=== `Profiles.Policy` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`min_base_template_version`
|String
|String
|The minimum base template version that the IQ Gateway (formerly "Envoy") must meet for this profile.

|`min_master_model_version`
|String
|String
|The minimum master model version that the IQ Gateway (formerly "Envoy") must meet for this profile.

|`min_envoy_version`
|String
|String
|The minimum Gateway (formerly "Envoy") version to use this profile.

|`max_envoy_version`
|String
|String
|The maximum Gateway (formerly "Envoy") version that is able to use this profile.

|`model_mismatch`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether to still try to make a profile, even if there is a version mismatch.

|`logical_device_mismatch`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether to still try to make a profle, even if the logical device cannot be found in the base template.

|`attribute_mismatch`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether to still try to make a profile, even if an attribute cannot be found in the base template.

|`id_mismatch`
|Boolean
|Boolean (e.g. `true` or `false`)
|Whether to update "opaque data" if the profile is otherwise the same.

|===

=== `Profile_groups` Object

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`GB`
|Array(Object)
|Array of `Profiles`
|Profiles applicable to Great Britain.

|`MT`
|Array(Object)
|Array of `Profiles`
|Profiles applicable to Malta.

|===

== Examples

=== List Uploaded Advanced Grid Functionality (AGF) Profile(s)

.GET */installer/agf/index.json* Response
[source,json,subs="+quotes"]
----
{"selected_profile": "G99-1-6:2020 UK:1.2.10", "selected_profile_id": "5f1502420508ca60028f5b74", "last_package_profile_md5sum": "ec5333f6de4878c4beadcce9de44f6b7", "profile_auto_selected": false, "mm_version": "01.03.00", "bt_version": "1.3.0", "migration_in_progress": false, "profiles": [{"uuid": "5f1502420508ca60028f5b74", "profile_id": "G99-1-6:2020 UK:1.2.10", "profile_name": "G99-1-6:2020 UK", "profile_version": "1.2.10", "profile_description": "G99-1-6:2020 'Base Profile' for the U.K.", "policy": {"min_base_template_version": "1.2.2", "min_master_model_version": "1.2.2", "min_envoy_version": "5.0", "max_envoy_version": "", "model_mismatch": false, "logical_device_mismatch": false, "attribute_mismatch": false, "id_mismatch": false}, "envoy_type": "europe", "countries": ["GB", "MT"], "states": [], "unpacked": true, "profile_source": ["enlighten"], "dynamic": true, "mm_version": "1.2.3", "bt_version": "1.2.3"}, {"uuid": "5f4e6b9d1b256058d86cab16", "profile_id": "G59-3-4:2018, G100-1-1:2017 PEL 3.68 kW:1.0.4", "profile_name": "G59-3-4:2018, G100-1-1:2017 PEL 3.68 kW", "profile_version": "1.0.4", "profile_description": "Copy of UK G100-1-1 Required for UK systems of 16A or larger (3.68kW).\r\nPEL soft limit of 3.68 kW at 5 s.", "policy": {"min_base_template_version": "1.0.2", "min_master_model_version": "1.0.2", "min_envoy_version": "4.4", "max_envoy_version": "", "model_mismatch": false, "logical_device_mismatch": false, "attribute_mismatch": false, "id_mismatch": false}, "envoy_type": "europe", "countries": ["GB"], "states": [], "unpacked": true, "profile_source": ["enlighten"], "dynamic": true, "mm_version": "1.0.2", "bt_version": "1.0.2"}], "profile_groups": {"GB": [{"uuid": "5f1502420508ca60028f5b74", "profile_id": "G99-1-6:2020 UK:1.2.10", "profile_name": "G99-1-6:2020 UK", "profile_version": "1.2.10", "profile_description": "G99-1-6:2020 'Base Profile' for the U.K.", "policy": {"min_base_template_version": "1.2.2", "min_master_model_version": "1.2.2", "min_envoy_version": "5.0", "max_envoy_version": "", "model_mismatch": false, "logical_device_mismatch": false, "attribute_mismatch": false, "id_mismatch": false}, "envoy_type": "europe", "countries": ["GB", "MT"], "states": [], "unpacked": true, "profile_source": ["enlighten"], "dynamic": true, "mm_version": "1.2.3", "bt_version": "1.2.3"}, {"uuid": "5f4e6b9d1b256058d86cab16", "profile_id": "G59-3-4:2018, G100-1-1:2017 PEL 3.68 kW:1.0.4", "profile_name": "G59-3-4:2018, G100-1-1:2017 PEL 3.68 kW", "profile_version": "1.0.4", "profile_description": "Copy of UK G100-1-1 Required for UK systems of 16A or larger (3.68kW).\r\nPEL soft limit of 3.68 kW at 5 s.", "policy": {"min_base_template_version": "1.0.2", "min_master_model_version": "1.0.2", "min_envoy_version": "4.4", "max_envoy_version": "", "model_mismatch": false, "logical_device_mismatch": false, "attribute_mismatch": false, "id_mismatch": false}, "envoy_type": "europe", "countries": ["GB"], "states": [], "unpacked": true, "profile_source": ["enlighten"], "dynamic": true, "mm_version": "1.0.2", "bt_version": "1.0.2"}], "MT": [{"uuid": "5f1502420508ca60028f5b74", "profile_id": "G99-1-6:2020 UK:1.2.10", "profile_name": "G99-1-6:2020 UK", "profile_version": "1.2.10", "profile_description": "G99-1-6:2020 'Base Profile' for the U.K.", "policy": {"min_base_template_version": "1.2.2", "min_master_model_version": "1.2.2", "min_envoy_version": "5.0", "max_envoy_version": "", "model_mismatch": false, "logical_device_mismatch": false, "attribute_mismatch": false, "id_mismatch": false}, "envoy_type": "europe", "countries": ["GB", "MT"], "states": [], "unpacked": true, "profile_source": ["enlighten"], "dynamic": true, "mm_version": "1.2.3", "bt_version": "1.2.3"}]}}
----