= Stream/Meter
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

A HTTP GET to `/stream/meter` can be used to get 22 "https://en.wikipedia.org/wiki/Server-sent_events[Server-Sent Events (SSE)]" (MIME type `text/event-stream`) formatted objects of the meter data every 22 seconds. This is presumably due to the Gateway polling every second but buffering the data (potentially a 16 KB = 16384 byte buffer?). This can be consumed by the `EventSource` JavaScript API.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../README.adoc[project's homepage].

== Request

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`production`
|Object
|`Phases` object
|An object that contains the production meter readings.

|`net-consumption`
|Object
|`Phases` object
|An object that contains the consumption meter readings for systems with solar production included.

|`total-consumption`
|Object
|`Phases` object
|An object that contains the consumption meter readings for systems measuring the load only.

|===

=== `Phases` Object

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`ph=a`
|Object
|`Phase` object
|Information for Phase A (or Phase 1).

|`ph=b`
|Object
|`Phase` object
|Information for Phase B (or Phase 2).

|`ph=c`
|Object
|`Phase` object
|Information for Phase C (or Phase 3).

|===

=== `Phase` Object

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`p`
|Number
|Number
|The number of watts currently being reported (elsewhere called `wNow`).

|`q`
|Number
|Number
|The reactive power value. The dissipated power resulting from inductive and capacitive loads measured in Volt-Amperes reactive (var) (elsewhere called `reactPwr`).

|`s`
|Number
|Number
|The apparent power value. The combination of reactive and true power measurement in Volt-Amperes (VA) (elsewhere called `apprntPwr`).

|`v`
|Number
|Number
|The Root Mean Square voltage value in Vrms (elsewhere called `rmsVoltage`).

|`i`
|Number
|Number
|The Root Mean Square current value in Amps (elsewhere called `rmsCurrent`).

|`pf`
|Number
|Number
|The power factor value. The ratio of the real power absorbed by the load to the apparent power flowing in the circuit (elsewhere called `pwrFactor`).

|`f`
|Number
|Number
|The frequency of the system (e.g. 50 Hz in the UK).

|===

== Examples

=== Get Meter Data
.GET */stream/meter* Response
[source,json,subs="+quotes"]
----
data: {"production":{"ph-a":{"p":-0.0,"q":175.922,"s":182.78,"v":239.055,"i":0.764,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":447.973,"q":-710.332,"s":907.001,"v":239.302,"i":3.787,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":447.973,"q":-886.254,"s":1088.562,"v":239.178,"i":4.551,"pf":0.41,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.06,"s":182.785,"v":238.953,"i":0.765,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":443.667,"q":-710.865,"s":903.193,"v":239.131,"i":3.766,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":443.667,"q":-886.926,"s":1083.188,"v":239.042,"i":4.531,"pf":0.41,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.274,"s":183.046,"v":239.027,"i":0.766,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":440.149,"q":-710.677,"s":900.245,"v":239.107,"i":3.758,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":440.149,"q":-886.951,"s":1081.694,"v":239.067,"i":4.525,"pf":0.41,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}

data: {"production":{"ph-a":{"p":-0.0,"q":175.497,"s":183.003,"v":239.23,"i":0.766,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":440.625,"q":-711.7,"s":899.396,"v":239.284,"i":3.762,"pf":0.5,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":440.625,"q":-887.197,"s":1083.306,"v":239.257,"i":4.528,"pf":0.41,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":175.358,"s":182.978,"v":239.213,"i":0.764,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":440.312,"q":-712.327,"s":899.571,"v":239.371,"i":3.758,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":440.312,"q":-887.684,"s":1082.108,"v":239.292,"i":4.522,"pf":0.41,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}

data: {"production":{"ph-a":{"p":-0.0,"q":175.074,"s":182.631,"v":239.083,"i":0.764,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":440.046,"q":-711.886,"s":899.4,"v":239.356,"i":3.756,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":440.046,"q":-886.961,"s":1081.202,"v":239.22,"i":4.52,"pf":0.41,"f":49.97},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":175.832,"s":182.398,"v":238.973,"i":0.763,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":436.669,"q":-711.464,"s":898.131,"v":239.241,"i":3.754,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":436.669,"q":-887.296,"s":1079.88,"v":239.107,"i":4.516,"pf":0.4,"f":49.97},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.133,"s":182.471,"v":238.928,"i":0.764,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":437.004,"q":-711.367,"s":898.549,"v":239.072,"i":3.758,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":437.004,"q":-887.499,"s":1080.712,"v":239.0,"i":4.522,"pf":0.4,"f":49.97},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":175.583,"s":182.601,"v":239.092,"i":0.765,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":438.094,"q":-711.386,"s":899.048,"v":239.132,"i":3.765,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":438.094,"q":-886.969,"s":1083.052,"v":239.112,"i":4.529,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.354,"s":183.017,"v":239.508,"i":0.764,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":438.626,"q":-713.054,"s":900.137,"v":239.552,"i":3.758,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":438.626,"q":-889.409,"s":1083.081,"v":239.53,"i":4.522,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.037,"s":183.519,"v":239.682,"i":0.768,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":437.578,"q":-713.86,"s":899.7,"v":239.87,"i":3.75,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":437.578,"q":-890.897,"s":1083.214,"v":239.776,"i":4.518,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.801,"s":183.856,"v":239.375,"i":0.768,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":435.145,"q":-714.05,"s":898.821,"v":239.632,"i":3.749,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":435.145,"q":-891.851,"s":1081.76,"v":239.504,"i":4.517,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.879,"s":183.567,"v":239.2,"i":0.766,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":433.313,"q":-712.466,"s":897.309,"v":239.393,"i":3.746,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":433.313,"q":-889.346,"s":1079.82,"v":239.297,"i":4.512,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.139,"s":183.158,"v":239.262,"i":0.765,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":433.604,"q":-711.944,"s":896.747,"v":239.344,"i":3.746,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":433.604,"q":-889.083,"s":1079.619,"v":239.303,"i":4.512,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.458,"s":183.196,"v":239.479,"i":0.765,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":434.777,"q":-712.939,"s":897.602,"v":239.521,"i":3.751,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":434.777,"q":-890.397,"s":1081.638,"v":239.5,"i":4.516,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.513,"s":183.313,"v":239.6,"i":0.766,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":434.257,"q":-713.064,"s":897.885,"v":239.749,"i":3.746,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":434.257,"q":-890.577,"s":1081.428,"v":239.674,"i":4.512,"pf":0.4,"f":49.97},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.513,"s":183.313,"v":239.6,"i":0.766,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":434.257,"q":-713.064,"s":897.885,"v":239.749,"i":3.746,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":434.257,"q":-890.577,"s":1081.428,"v":239.674,"i":4.512,"pf":0.4,"f":49.97},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":177.744,"s":183.477,"v":239.397,"i":0.766,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":433.582,"q":-713.161,"s":897.58,"v":239.665,"i":3.742,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":433.582,"q":-890.905,"s":1079.857,"v":239.531,"i":4.508,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.922,"s":183.464,"v":239.105,"i":0.767,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":431.308,"q":-712.777,"s":896.097,"v":239.37,"i":3.742,"pf":0.48,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":431.308,"q":-889.699,"s":1078.619,"v":239.237,"i":4.509,"pf":0.4,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.936,"s":183.259,"v":239.054,"i":0.766,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":430.686,"q":-711.485,"s":895.449,"v":239.2,"i":3.742,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":430.686,"q":-888.422,"s":1078.128,"v":239.127,"i":4.509,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":176.807,"s":183.08,"v":239.253,"i":0.764,"pf":0.0,"f":50.0},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":431.883,"q":-712.632,"s":896.521,"v":239.297,"i":3.749,"pf":0.48,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":431.883,"q":-889.439,"s":1079.955,"v":239.275,"i":4.513,"pf":0.4,"f":49.97},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


data: {"production":{"ph-a":{"p":-0.0,"q":175.087,"s":182.779,"v":239.519,"i":0.763,"pf":0.0,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"net-consumption":{"ph-a":{"p":434.237,"q":-714.279,"s":898.431,"v":239.549,"i":3.756,"pf":0.49,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}},"total-consumption":{"ph-a":{"p":434.237,"q":-889.366,"s":1082.296,"v":239.534,"i":4.518,"pf":0.4,"f":49.94},"ph-b":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0},"ph-c":{"p":0.0,"q":0.0,"s":0.0,"v":0.0,"i":0.0,"pf":0.0,"f":0.0}}}


----