= Version 1 API (Legacy) - Inverter(s) Production (Version 1 API)
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Obtain the legacy microinverter energy production information.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the xref:../../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/api/v1/production/inverters` endpoint provides the following response data.

As of recent Gateway software versions this request requires user authentication and authorisation, see xref:../../Authentication.adoc[Authentication].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`serialNumber`
|String
|String
|The serial number of this microinverter.

|`lastReportDate`
|Number
|Number
|The last time this microinverter reported in (in epoch date and time format).

|`devType`
|Number
|Number
|The device type.

|`lastReportWatts`
|Number
|Number
|The power (in Watts) this observed when it last reported in.

|`maxReportWatts`
|Number
|Number
|The highest power (in Watts) this device has ever seen.

|===

== Examples

=== Get Legacy Production Data

.GET */api/v1/production/inverters* Response
[source,json,subs="+quotes"]
----
[{"serialNumber": "123456789011", "lastReportDate": 1685910322, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789012", "lastReportDate": 1685910360, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789013", "lastReportDate": 1685910295, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789014", "lastReportDate": 1685910329, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789015", "lastReportDate": 1685910367, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789016", "lastReportDate": 1685910507, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789017", "lastReportDate": 1685910512, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789018", "lastReportDate": 1685910337, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789019", "lastReportDate": 1685910518, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789021", "lastReportDate": 1685910280, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789022", "lastReportDate": 1685910282, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789023", "lastReportDate": 1685910286, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789024", "lastReportDate": 1685910285, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}, {"serialNumber": "123456789025", "lastReportDate": 1685910288, "devType": 1, "lastReportWatts": 0, "maxReportWatts": 367}]
----