= Installer - General - Power Conditioning Unit (PCU) Communication Check
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Check communication with the microinverter(s) (also called "Power Conditioning Unit(s) (PCU)").

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/installer/pcu_comm_check` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`{serial_num}`
|Number
|Number
|The Power-Line Communication (PLC) communication level of this Power Conditioning Unit (or "microinverter").

|===

== Examples

=== Perform Power Conditioning Unit (PCU) Communication Check

.GET */installer/pcu_comm_check* Response
[listing]
----
{"123456789101": 5, "123456789102": 5, "123456789103": 5, "123456789104": 5, "123456789105": 5, "123456789106": 5, "123456789107": 5, "123456789108": 5, "123456789109": 5, "123456789110": 5, "123456789111": 5, "123456789112": 5, "123456789113": 5, "123456789114": 5}
----