= Installer - General - Secure SHell (SSH) Revoke List
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Get the list of Secure SHell (SSH) revoked keys.

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../../README.adoc[project's homepage].

== Request

A HTTP `GET` to the `/installer/ssh_revoke_list` endpoint provides the following response data.

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

[cols="1,1,1,2", options="header"]
|===
|Name
|Type
|Values
|Description

|`sig`
|String
|String
|The KRL signature (ECDSA?).

|`date`
|String
|String
|The date (in epoch format).

|`serno`
|String
|String
|The serial number of the Key Revocation List (KRL).

|`crl`
|String
|String
|The SSH Key Revocation List (KRL).

|===

== Examples

=== Get Secure SHell (SSH) Revoke List

.GET */installer/ssh_revoke_list* Response
[source,json,subs="+quotes"]
----
{"sig": "MEYCIQDqsDkPsOQio9oDco1zfsfztzvHKv9boNQbA2Oi9zxSQwIhAKFi6WGq2W4X2wsb/3oaQLI45thL0MClE9fgTIjMWKxA", "date": "1637812398", "serno": "4", "crl": "U1NIS1JMCgAAAAABAAAAAAAAAAAAAAAAYZ8IHgAAAAAAAAAAAAAAAAAAAAABAAABLAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAPQ0b8RU5nJebzJpUOSCso/kwbjacwJ9lxRkhFv5Ek+WGRM89JrTvp0cfRXCxgsvgxjBf9WWPK2nmGQ5LGpIPzBXxGXfGm8rtpIPiTAL7tz0g2eoBDrSUHuQQdixBKiYKoHAeSlL/x6W6+a2VNRlTxu40hv3zudPD5XbD0OW3G2qcEHcGsSB8JUnIvuDkqEXYaEaNw3xCjBWThH8QWZjEIsY2ajh2JVswHhsNDIzeUCx3VxMuYDgoftHD5UXh0Haji18oP/gN8jR9s6TXAeORPlBQq0V6WoRTeHVw+bLDBhQdUc2NsDkEhivoJRT5lh0UJjwfLvQpW2hYOLT1l+NAoMAAAAAIAAAAAgAAAAAAAAAng=="}
----