= Authentication - Check JSON Web Token (JWT)
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON by default.
:source-language: json

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

Checks a user is authenticated and authorised.

== Introduction

This endpoint is a simple endpoint that requires a user to be authenticated and so is a good endpoint to check a user is authenticated or to perform authentication as a side effect.

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the xref:../../../README.adoc[project's homepage].

== Details

This simple endpoint is configured to require any authentication.

It simply invokes the standard xref:../Authentication.adoc[system wide authentication check].

If the authentication fails the user is met with a `Authorization Required` error. Should it succeed then the user will be diverted to the hidden endpoint `/valid_token` which just returns static text.

As JWT validation is more intensive it is preferred to use this end-point to create a session and then for all subsequent API requests (of varying resource intensity) to just use the `sessionId` cookie to authenticate.


== Request

A HTTP `GET` to the `/auth/check_jwt` endpoint provides the following response data.

As of recent Gateway software versions this request requires user authentication and authorisation, see xref:../Authentication.adoc[Authentication].

== Examples

=== Check Authenticated (Success)

.GET */auth/check_jwt* Response
[listing]
----
<!DOCTYPE html><h2>Valid token.</h2>
----

=== Check Authenticated (Failure)

.GET */auth/check_jwt* Response
[listing]
----
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>Redirecting to <a id='link' href=''></a></center>
<script>
const redirect_url = window.location.protocol + '//' + window.location.host + '/home';
function redirect() { window.location.href = redirect_url; }
window.onload = function() {
    const link = document.getElementById('link');
    link.href = redirect_url;
    link.text = redirect_url;
    setTimeout(redirect, 500);
}
</script>
</body>
</html>

----