= IVP/PEB/NewScan
:toc: preamble
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code blocks will be in JSON5 by default.
:source-language: json5

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/Enphase-API
:url-contributors: {url-repo}/graphs/contributors

A HTTP GET to `/ivp/peb/newscan` can be used to get details about the scan for Power Electronics Blocks (PEB).

== Introduction

Enphase-API is an unofficial project providing an API wrapper and the documentation for Enphase(R)'s products and services.

More details on the project are available from the link:../../README.adoc[project's homepage].

== Request

As of recent Gateway software versions this request requires a valid `sessionid` cookie obtained by link:../../Auth/Check_JWT.adoc[Auth/Check_JWT].

== Response

=== Root

To be completed.

== Examples

=== Get NewScan Example

.PUT */ivp/peb/newscan* Response
[source,json5,subs="+quotes"]
----
{ "newDeviceScan" : { "active" : false, "is-suspended" : false, "controlled" : false, "scan-is-done" : false, "in-exclusive-mode" : false, "duration-in-minutes" : 0, "remaining-minutes" : 0, "exclusive-minutes" : 0, "rem-minutes-exclusive" : 0, "inhibit-device-scan" : false, "rqst-opportunity-modulus" : 0, "curr-opportunity-modulus" : 0, "devices-to-be-discovered" : 10, "tot-devices-discovered" : 10, "curr-devices-discovered" : 10, "avg-rate-of-new-devices-discovered-per-min" : 10, "avg-num-of-new-devices-discovered-per-poll" : 10, "pcu": {"expected": 10, "discovered": 10, "this-scan": 10, "per-min": 10, "per-poll": 10}, "acb": {"expected": 0, "discovered": 0, "this-scan": 0, "per-min": 0, "per-poll": 0}, "nsrb": {"expected": 0, "discovered": 0, "this-scan": 0, "per-min": 0, "per-poll": 0}, "esub": {"expected": 0, "discovered": 0, "this-scan": 0, "per-min": 0, "per-poll": 0}, "pld": {"expected": 10, "discovered": 10, "this-scan": 10, "per-min": 10, "per-poll": 10}, "mins-until-next-cycle" : 5, "xdom-disabled-scan" : false, "polling-period-secs" : 900, "polling-is-off" : false,"forget-all-scan" : false }}
----